---

- name: Set zookeeper to port 2191
  lineinfile:
    dest: /etc/zookeeper/conf/zoo.cfg
    regexp: "^clientPort="
    line: "clientPort=2191"

- name: restart zookeeper
  service: name=zookeeper state=restarted

- set_fact:
    macvlanIP: "{{ ansible_macvlan0['ipv4']['address'] }}"

- name: Set Docker store
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "^ExecStart="
    line: "ExecStart=/usr/bin/dockerd -H fd:// --cluster-store=zk://{{ macvlanIP }}:2191 --cluster-advertise={{ macvlanIP }}:2376"

- name: reload docker daemon
  command: systemctl daemon-reload

- name: restart docker
  service: state=restarted name=docker
